# Generated by Django 2.2.4 on 2019-08-19 18:02

import app_gp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to=app_gp.models.profile_upload_path, verbose_name='Imagem de Perfil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=app_gp.models.thumb_upload_path, verbose_name='Thumb'),
        ),
    ]
