# Generated by Django 2.2.4 on 2019-08-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclientactingcities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesCity', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='interclientactingcities',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.Client', verbose_name='Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='interclientactingcities',
            unique_together={('client', 'city')},
        ),
    ]
