# Generated by Django 2.2.1 on 2019-08-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclientactingcities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', related_query_name='city', to='app_gp.ChoicesCity', verbose_name='Cidade'),
        ),
    ]
