# Generated by Django 2.2.4 on 2019-08-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intercitysit',
            unique_together={('city', 'sit_number', 'client')},
        ),
    ]
