# Generated by Django 2.2.4 on 2019-08-28 18:48

import app_gp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicesstates',
            name='id',
        ),
        migrations.AlterField(
            model_name='choicesstates',
            name='ibge_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='clientphoto',
            name='photo',
            field=models.ImageField(upload_to=app_gp.models.photos_upload_path, verbose_name='Fotos'),
        ),
        migrations.AlterField(
            model_name='clientvideo',
            name='video',
            field=models.FileField(upload_to=app_gp.models.videos_upload_path, verbose_name='Videos'),
        ),
    ]
