# Generated by Django 2.2.4 on 2019-08-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'db_table': 'choices_question',
                'ordering': ['question'],
            },
        ),
    ]
