# Generated by Django 2.2.4 on 2019-08-30 17:39

import app_gp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=app_gp.models.highlight_photo_upload_path, verbose_name='Foto destaque')),
                ('highlight_type', models.CharField(choices=[('1', 'Top'), ('2', 'Left'), ('3', 'Right'), ('4', 'Bottom')], max_length=50)),
                ('order_priority', models.PositiveIntegerField(verbose_name='Prioridade da foto')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesCity')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesGenre')),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'db_table': 'highlight',
                'ordering': ['city', 'genre', 'order_priority'],
                'unique_together': {('city', 'genre', 'order_priority')},
            },
        ),
    ]
