# Generated by Django 2.2.4 on 2019-08-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190812_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesNeighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesCity', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'db_table': 'choices_neighborhoods',
                'ordering': ['neighborhood'],
            },
        ),
    ]
