# Generated by Django 2.2.4 on 2019-08-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_highlights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highlights',
            new_name='Highlight',
        ),
    ]
