# Generated by Django 2.2.4 on 2019-08-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190808_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'choices_status',
                'ordering': ['status'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesEthnicity', verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesEyeColor', verbose_name='Olhos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesGenre', verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesStatus', verbose_name='Status'),
        ),
    ]
