# Generated by Django 2.2.1 on 2019-08-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190804_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclientactingcities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesCity', verbose_name='Cidade'),
        ),
    ]
