# Generated by Django 2.2.4 on 2019-08-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190819_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesgenre',
            name='representative_image',
            field=models.ImageField(blank=True, null=True, upload_to='Media', verbose_name='Imagem representativa'),
        ),
        migrations.AddField(
            model_name='choicesgenre',
            name='site_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome no site'),
            preserve_default=False,
        ),
    ]
