# Generated by Django 2.2.4 on 2019-08-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190813_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='teste',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teste', to='app_gp.ChoicesGenre', verbose_name='Gênero'),
        ),
    ]
