# Generated by Django 2.2.4 on 2019-08-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0002_auto_20190815_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesCity', verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='profile_priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Prioridade do Profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('city', 'genre', 'profile_priority')},
        ),
    ]
