# Generated by Django 2.2.4 on 2019-08-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_client_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='intercitysit',
            name='id',
        ),
        migrations.AlterField(
            model_name='intercitysit',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_gp.Client'),
        ),
    ]
