# Generated by Django 2.2.4 on 2019-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_auto_20190819_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular'),
        ),
    ]
