# Generated by Django 2.2.1 on 2019-08-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_auto_20190804_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesEthnicity', verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesEyeColor', verbose_name='Olhos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gp.ChoicesGenre', verbose_name='Gênero'),
        ),
    ]
