# Generated by Django 2.2.4 on 2019-08-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_choicesneighborhoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicescity',
            options={'ordering': ['state', 'city'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='choicesneighborhoods',
            options={'ordering': ['city', 'neighborhood'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
    ]
