# Generated by Django 2.2.4 on 2019-08-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_auto_20190810_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesHairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair', models.CharField(max_length=50, verbose_name='Cor do cabelo')),
            ],
            options={
                'verbose_name': 'Cor de cabelo',
                'verbose_name_plural': 'Cores de cabelo',
                'db_table': 'choices_hair_color',
                'ordering': ['hair'],
            },
        ),
    ]
