# Generated by Django 2.2.4 on 2019-08-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0003_auto_20190815_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['genre', 'profile_priority'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesGenre', verbose_name='Gênero'),
            preserve_default=False,
        ),
    ]
