# Generated by Django 2.2.4 on 2019-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='foot',
            field=models.FloatField(blank=True, null=True, verbose_name='Pés'),
        ),
        migrations.AddField(
            model_name='client',
            name='hip',
            field=models.FloatField(blank=True, null=True, verbose_name='Quadril(cm)'),
        ),
    ]
