# Generated by Django 2.2.4 on 2019-08-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_choiceshaircolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceseyecolor',
            options={'ordering': ['eye_color'], 'verbose_name': 'Cor do olho', 'verbose_name_plural': 'Cores dos olhos'},
        ),
        migrations.AlterModelOptions(
            name='choiceshaircolor',
            options={'ordering': ['hair_color'], 'verbose_name': 'Cor de cabelo', 'verbose_name_plural': 'Cores de cabelo'},
        ),
        migrations.RenameField(
            model_name='choiceshaircolor',
            old_name='hair',
            new_name='hair_color',
        ),
        migrations.RemoveField(
            model_name='choiceseyecolor',
            name='color',
        ),
        migrations.AddField(
            model_name='choiceseyecolor',
            name='eye_color',
            field=models.CharField(default=1, max_length=75, verbose_name='Cor do olho'),
            preserve_default=False,
        ),
    ]
