# Generated by Django 2.2.1 on 2019-08-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_auto_20190805_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interclientactingcities',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_city', to='app_gp.ChoicesCity', verbose_name='Cidade'),
        ),
    ]
