# Generated by Django 2.2.4 on 2019-08-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_auto_20190813_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercitysit',
            options={'ordering': ['city', 'sit_number'], 'verbose_name': 'Ordem do clientes', 'verbose_name_plural': 'Ordens dos clientes'},
        ),
        migrations.AlterField(
            model_name='intercitysit',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesCity', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='intercitysit',
            name='sit_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesSitNumber', verbose_name='Posição'),
        ),
        migrations.AlterUniqueTogether(
            name='intercitysit',
            unique_together={('city', 'sit_number')},
        ),
    ]
