# Generated by Django 2.2.4 on 2019-08-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_auto_20190830_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gp.Client'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_type',
            field=models.CharField(choices=[('1', 'top'), ('2', 'left'), ('3', 'right'), ('4', 'bottom')], max_length=50),
        ),
    ]
