# Generated by Django 2.2.4 on 2019-08-12 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0004_auto_20190812_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesSitNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_number', models.IntegerField(verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
                'db_table': 'choices_sit_number',
                'ordering': ['sit_number'],
            },
        ),
        migrations.CreateModel(
            name='ClientCitySitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesCity')),
                ('sit_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ChoicesSitNumber')),
            ],
            options={
                'verbose_name': 'Ordem do clientes',
                'verbose_name_plural': 'Ordens dos clientes',
                'db_table': 'client_city_sit_order',
                'ordering': ['sit_number', 'city'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_city_sit_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_gp.ClientCitySitOrder', verbose_name='cidade'),
        ),
    ]
