# Generated by Django 2.2.4 on 2019-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0005_auto_20190813_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='customer_services',
            field=models.ManyToManyField(db_table='inter_client_customer_services', related_name='client_customer_service_rel', to='app_gp.ChoicesCustomerService', verbose_name='Atendimentos'),
        ),
    ]
