# Generated by Django 2.2.1 on 2019-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0005_auto_20190805_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Indentificador'),
        ),
    ]
