# Generated by Django 2.2.4 on 2019-08-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0005_auto_20190812_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_city_sit_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_order', to='app_gp.ClientCitySitOrder', verbose_name='cidade'),
        ),
    ]
