# Generated by Django 2.2.4 on 2019-08-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gp', '0006_auto_20190830_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gp.Client'),
        ),
    ]
